//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestAdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        public ProductGroup()
        {
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int ProductGroupPK { get; set; }
        public int CustomerFK { get; set; }
        public string ProductGroupName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
