/**
 * ICustomerManagementService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.microsoft.adcenter.api.customermanagement;

public interface ICustomerManagementService extends java.rmi.Remote {
    public com.microsoft.adcenter.api.customermanagement.GetAccountsInfoResponse getAccountsInfo(com.microsoft.adcenter.api.customermanagement.GetAccountsInfoRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.FindAccountsResponse findAccounts(com.microsoft.adcenter.api.customermanagement.FindAccountsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.AddAccountResponse addAccount(com.microsoft.adcenter.api.customermanagement.AddAccountRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.UpdateAccountResponse updateAccount(com.microsoft.adcenter.api.customermanagement.UpdateAccountRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetCustomerResponse getCustomer(com.microsoft.adcenter.api.customermanagement.GetCustomerRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.UpdateCustomerResponse updateCustomer(com.microsoft.adcenter.api.customermanagement.UpdateCustomerRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.SignupCustomerResponse signupCustomer(com.microsoft.adcenter.api.customermanagement.SignupCustomerRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetAccountResponse getAccount(com.microsoft.adcenter.api.customermanagement.GetAccountRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetCustomersInfoResponse getCustomersInfo(com.microsoft.adcenter.api.customermanagement.GetCustomersInfoRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.AddUserResponse addUser(com.microsoft.adcenter.api.customermanagement.AddUserRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.DeleteAccountResponse deleteAccount(com.microsoft.adcenter.api.customermanagement.DeleteAccountRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.DeleteCustomerResponse deleteCustomer(com.microsoft.adcenter.api.customermanagement.DeleteCustomerRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.UpdateUserResponse updateUser(com.microsoft.adcenter.api.customermanagement.UpdateUserRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.UpdateUserRolesResponse updateUserRoles(com.microsoft.adcenter.api.customermanagement.UpdateUserRolesRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetUserResponse getUser(com.microsoft.adcenter.api.customermanagement.GetUserRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetCurrentUserResponse getCurrentUser(com.microsoft.adcenter.api.customermanagement.GetCurrentUserRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.DeleteUserResponse deleteUser(com.microsoft.adcenter.api.customermanagement.DeleteUserRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetUsersInfoResponse getUsersInfo(com.microsoft.adcenter.api.customermanagement.GetUsersInfoRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetCustomerPilotFeatureResponse getCustomerPilotFeature(com.microsoft.adcenter.api.customermanagement.GetCustomerPilotFeatureRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetPilotFeaturesCountriesResponse getPilotFeaturesCountries(com.microsoft.adcenter.api.customermanagement.GetPilotFeaturesCountriesRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetAccessibleCustomerResponse getAccessibleCustomer(com.microsoft.adcenter.api.customermanagement.GetAccessibleCustomerRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.FindAccountsOrCustomersInfoResponse findAccountsOrCustomersInfo(com.microsoft.adcenter.api.customermanagement.FindAccountsOrCustomersInfoRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.UpgradeCustomerToAgencyResponse upgradeCustomerToAgency(com.microsoft.adcenter.api.customermanagement.UpgradeCustomerToAgencyRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.SendRequestToManageAccountsResponse sendRequestToManageAccounts(com.microsoft.adcenter.api.customermanagement.SendRequestToManageAccountsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.AcceptRequestToManageAccountsResponse acceptRequestToManageAccounts(com.microsoft.adcenter.api.customermanagement.AcceptRequestToManageAccountsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.CancelRequestToManageAccountsResponse cancelRequestToManageAccounts(com.microsoft.adcenter.api.customermanagement.CancelRequestToManageAccountsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.SendRequestToStopManagingAccountsResponse sendRequestToStopManagingAccounts(com.microsoft.adcenter.api.customermanagement.SendRequestToStopManagingAccountsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetRequestToManageAccountsResponse getRequestToManageAccounts(com.microsoft.adcenter.api.customermanagement.GetRequestToManageAccountsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.GetRequestToManageAccountsInfosResponse getRequestToManageAccountsInfos(com.microsoft.adcenter.api.customermanagement.GetRequestToManageAccountsInfosRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.DeclineRequestToManageAccountsResponse declineRequestToManageAccounts(com.microsoft.adcenter.api.customermanagement.DeclineRequestToManageAccountsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.AddPrepayAccountResponse addPrepayAccount(com.microsoft.adcenter.api.customermanagement.AddPrepayAccountRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.MapCustomerIdToExternalCustomerIdResponse mapCustomerIdToExternalCustomerId(com.microsoft.adcenter.api.customermanagement.MapCustomerIdToExternalCustomerIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
    public com.microsoft.adcenter.api.customermanagement.MapAccountIdToExternalAccountIdsResponse mapAccountIdToExternalAccountIds(com.microsoft.adcenter.api.customermanagement.MapAccountIdToExternalAccountIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.api.customermanagement.Exception.ApiFault;
}
