//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisingEngineAd
    {
        public long AdvertisingEngineAdPK { get; set; }
        public int PromotionAdsFK { get; set; }
        public int AdvertisingEngineFK { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AdvertisingEngine AdvertisingEngine { get; set; }
        public virtual PromotionAd PromotionAd { get; set; }
    }
}
