//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetedDailyBudget
    {
        public int TargetedDailyBudgetPK { get; set; }
        public long TargetedDailyMicroBudget { get; set; }
        public int TargetedDailyClicks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int PromotionFK { get; set; }
        public int AdvertisingEngineFK { get; set; }
        public Nullable<long> TargetedMicroCPC { get; set; }
    
        public virtual AdvertisingEngine AdvertisingEngine { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
