#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResources.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Password.cshtml")]
    public class Password : System.Web.Mvc.WebViewPage<Semplest.SharedResources.Models.ProfileModel>
    {
        public Password()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n           <div class=\"editor-label\">\r\n                ");


            
            #line 4 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.LabelFor(m => m.Password2));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n                        <div class=\"editor-field\">\r\n       " +
"         ");


            
            #line 7 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.TextBoxFor(m => m.Password2, new { @class = "k-textbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 8 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.ValidationMessageFor(m => m.Password2));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n           <div class=\"editor-label\">\r\n                ");


            
            #line 11 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.LabelFor(m => m.Password3));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n                   <div class=\"editor-field\">\r\n          " +
"      ");


            
            #line 15 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.PasswordFor(m => m.Password3, new { @class = "k-textbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 16 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.ValidationMessageFor(m => m.Password3));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n\r\n\r\n\r\n           <div class=\"editor-label\">\r\n        " +
"        ");


            
            #line 23 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.LabelFor(m => m.SecurityQuestion));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


            
            #line 26 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.TextBoxFor(m => m.SecurityQuestion, new { @class = "k-textbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 27 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.ValidationMessageFor(m => m.SecurityQuestion));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n           <div class=\"editor-label\">\r\n                ");


            
            #line 31 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.LabelFor(m => m.SecurityAnswer));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


            
            #line 34 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.TextBoxFor(m => m.SecurityAnswer, new { @class = "k-textbox" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 35 "..\..\Views\Shared\_Password.cshtml"
           Write(Html.ValidationMessageFor(m => m.SecurityAnswer));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n\r\n\r\n\r\n        <br />\r\n        <br />\r\n        <button cla" +
"ss=\"k-button\" id=\"get\">Create Account</button>\r\n\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
