//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CustomerAddressAssociation))]
    public partial class AddressType
    {
        public AddressType()
        {
            this.CustomerAddressAssociations = new HashSet<CustomerAddressAssociation>();
        }
    
        [DataMember]
        public int AddressTypePK { get; set; }
        [DataMember]
        public string AddressType1 { get; set; }
    
        [DataMember]
        public virtual ICollection<CustomerAddressAssociation> CustomerAddressAssociations { get; set; }
    }
    
}
