//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;


namespace SemplestModel
{
    
    public partial class AdvertisingEngine
    {
        public AdvertisingEngine()
        {
            this.AdvertisingEngineAccounts = new HashSet<AdvertisingEngineAccount>();
            this.AdvertisingEngineAds = new HashSet<AdvertisingEngineAd>();
            this.KeywordBids = new HashSet<KeywordBid>();
            this.PromotionAdEngineSelecteds = new HashSet<PromotionAdEngineSelected>();
            this.PromotionAdengineStatus = new HashSet<PromotionAdengineStatu>();
            this.TargetedDailyBudgets = new HashSet<TargetedDailyBudget>();
        }
    
        [DataMember,Key]
        public int AdvertisingEnginePK { get; set; }

        [Column("AdvertisingEngine")]
        public string AdvertisingEngine1 { get; set; }
        
        public string LogoURL { get; set; }
    
        
        public virtual ICollection<AdvertisingEngineAccount> AdvertisingEngineAccounts { get; set; }
        
        public virtual ICollection<AdvertisingEngineAd> AdvertisingEngineAds { get; set; }
        
        public virtual ICollection<KeywordBid> KeywordBids { get; set; }
        
        public virtual ICollection<PromotionAdEngineSelected> PromotionAdEngineSelecteds { get; set; }
        
        public virtual ICollection<PromotionAdengineStatu> PromotionAdengineStatus { get; set; }
        
        public virtual ICollection<TargetedDailyBudget> TargetedDailyBudgets { get; set; }
    }
    
}
