//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisingEngineReportData
    {
        public int AdvertisingEngineBidDataPK { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int MicroBidAmount { get; set; }
        public int NumberImpressions { get; set; }
        public int NumberClick { get; set; }
        public double AveragePosition { get; set; }
        public long AverageCPC { get; set; }
        public Nullable<int> BidTypeFK { get; set; }
        public Nullable<int> QualityScore { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<int> FirstPageMicroCPC { get; set; }
        public Nullable<int> MicroCost { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> CostAppliedToPromotionDate { get; set; }
        public int KeywordFK { get; set; }
        public int PromotionFK { get; set; }
        public int AdvertisingEngineFK { get; set; }
    
        public virtual AdvertisingEngine AdvertisingEngine { get; set; }
        public virtual BidType BidType { get; set; }
        public virtual Keyword Keyword { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
