//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(AdvertisingEngine))]
    [KnownType(typeof(AdvertisingEnginePromotion))]
    [KnownType(typeof(Customer))]
    public partial class AdvertisingEngineAccount
    {
        public AdvertisingEngineAccount()
        {
            this.AdvertisingEnginePromotions = new HashSet<AdvertisingEnginePromotion>();
        }
    
        [DataMember]
        public long AdvertisingEngineAccountPK { get; set; }
        [DataMember]
        public int AdvertisingEngineFK { get; set; }
        [DataMember]
        public int CustomerFK { get; set; }
    
        [DataMember]
        public virtual AdvertisingEngine AdvertisingEngine { get; set; }
        [DataMember]
        public virtual ICollection<AdvertisingEnginePromotion> AdvertisingEnginePromotions { get; set; }
        [DataMember]
        public virtual Customer Customer { get; set; }
    }
    
}
