//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class AdvertisingEnginePromotion
    {
        #region Primitive Properties
    
        public virtual long AdvertisingEngineCampaignPK
        {
            get;
            set;
        }
    
        public virtual int PromotionFK
        {
            get { return _promotionFK; }
            set
            {
                if (_promotionFK != value)
                {
                    if (Promotion != null && Promotion.PromotionPK != value)
                    {
                        Promotion = null;
                    }
                    _promotionFK = value;
                }
            }
        }
        private int _promotionFK;
    
        public virtual long AdvertisingEngineAccountFK
        {
            get { return _advertisingEngineAccountFK; }
            set
            {
                if (_advertisingEngineAccountFK != value)
                {
                    if (AdvertisingEngineAccount != null && AdvertisingEngineAccount.AdvertisingEngineAccountPK != value)
                    {
                        AdvertisingEngineAccount = null;
                    }
                    _advertisingEngineAccountFK = value;
                }
            }
        }
        private long _advertisingEngineAccountFK;
    
        public virtual bool IsSearchNetwork
        {
            get;
            set;
        }
    
        public virtual bool IsDisplayNetwork
        {
            get;
            set;
        }
    
        public virtual decimal AdvertisingEngineBudget
        {
            get;
            set;
        }
    
        public virtual int MicroDefaultBid
        {
            get;
            set;
        }
    
        public virtual Nullable<long> AdvertisingEngineAdGroupID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual AdvertisingEngineAccount AdvertisingEngineAccount
        {
            get { return _advertisingEngineAccount; }
            set
            {
                if (!ReferenceEquals(_advertisingEngineAccount, value))
                {
                    var previousValue = _advertisingEngineAccount;
                    _advertisingEngineAccount = value;
                    FixupAdvertisingEngineAccount(previousValue);
                }
            }
        }
        private AdvertisingEngineAccount _advertisingEngineAccount;
    
        public virtual Promotion Promotion
        {
            get { return _promotion; }
            set
            {
                if (!ReferenceEquals(_promotion, value))
                {
                    var previousValue = _promotion;
                    _promotion = value;
                    FixupPromotion(previousValue);
                }
            }
        }
        private Promotion _promotion;

        #endregion
        #region Association Fixup
    
        private void FixupAdvertisingEngineAccount(AdvertisingEngineAccount previousValue)
        {
            if (previousValue != null && previousValue.AdvertisingEnginePromotions.Contains(this))
            {
                previousValue.AdvertisingEnginePromotions.Remove(this);
            }
    
            if (AdvertisingEngineAccount != null)
            {
                if (!AdvertisingEngineAccount.AdvertisingEnginePromotions.Contains(this))
                {
                    AdvertisingEngineAccount.AdvertisingEnginePromotions.Add(this);
                }
                if (AdvertisingEngineAccountFK != AdvertisingEngineAccount.AdvertisingEngineAccountPK)
                {
                    AdvertisingEngineAccountFK = AdvertisingEngineAccount.AdvertisingEngineAccountPK;
                }
            }
        }
    
        private void FixupPromotion(Promotion previousValue)
        {
            if (previousValue != null && previousValue.AdvertisingEnginePromotions.Contains(this))
            {
                previousValue.AdvertisingEnginePromotions.Remove(this);
            }
    
            if (Promotion != null)
            {
                if (!Promotion.AdvertisingEnginePromotions.Contains(this))
                {
                    Promotion.AdvertisingEnginePromotions.Add(this);
                }
                if (PromotionFK != Promotion.PromotionPK)
                {
                    PromotionFK = Promotion.PromotionPK;
                }
            }
        }

        #endregion
    }
}
