//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class AdvertisingEngineAccount
    {
        public AdvertisingEngineAccount()
        {
            this.AdvertisingEnginePromotions = new HashSet<AdvertisingEnginePromotion>();
        }
    
        [DataMember,Key]
        public long AdvertisingEngineAccountPK { get; set; }
        
        public int AdvertisingEngineFK { get; set; }
        
        public int CustomerFK { get; set; }

        [ForeignKey("AdvertisingEngineFK")]
        public virtual AdvertisingEngine AdvertisingEngine { get; set; }
        
        public virtual ICollection<AdvertisingEnginePromotion> AdvertisingEnginePromotions { get; set; }
        [ForeignKey("CustomerFK")]
        public virtual Customer Customer { get; set; }
    }
    
}
