//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class BidType
    {
        public BidType()
        {
            this.AdvertisingEngineReportDatas = new HashSet<AdvertisingEngineReportData>();
            this.KeywordBids = new HashSet<KeywordBid>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public int BidTypePK { get; set; }
        
        public string BidType1 { get; set; }
    
        
        public virtual ICollection<AdvertisingEngineReportData> AdvertisingEngineReportDatas { get; set; }
        
        public virtual ICollection<KeywordBid> KeywordBids { get; set; }
    }
    
}
