//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class Configuration
    {
        #region Primitive Properties
    
        public virtual int ConfigurationPK
        {
            get;
            set;
        }
    
        public virtual decimal CustomerMinOrderAmount
        {
            get;
            set;
        }
    
        public virtual decimal CustomerDefaultMonthlyFlatFeeAmount
        {
            get;
            set;
        }
    
        public virtual decimal CustomerDefaultPerCampaignFlatFeeAmount
        {
            get;
            set;
        }
    
        public virtual decimal CustomerDefaultPerAdGroupFlatFeeAmount
        {
            get;
            set;
        }
    
        public virtual decimal DefaultMediaComissionPercentage
        {
            get;
            set;
        }
    
        public virtual decimal DefaultSalesPersonCommissionPercentage
        {
            get;
            set;
        }
    
        public virtual decimal MinSalespersonCommissionPercentage
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> MaxSalespersonCommissionPercentage
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> DefalutBudgetMixPercentageGoogle
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> DefalutBudgetMixPercentageBing
        {
            get;
            set;
        }
    
        public virtual string DefaultSemplestBannerImageUrl
        {
            get;
            set;
        }
    
        public virtual string DefaultSemplestStyleSheetUrl
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MaxNumberOfSitelinks
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LastAccountNumberUsed
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LastSEMplestEmployeeIDused
        {
            get;
            set;
        }
    
        public virtual string DefaultEmailContactUs
        {
            get;
            set;
        }
    
        public virtual string DefalutEmailContactMe
        {
            get;
            set;
        }
    
        public virtual string DefaultProductGroupName
        {
            get;
            set;
        }
    
        public virtual string DefaultProductPromotionName
        {
            get;
            set;
        }
    
        public virtual string SamplestDevelopmentEmail
        {
            get;
            set;
        }
    
        public virtual string SemplestDefaultBudgetMarkUpOrDown
        {
            get;
            set;
        }
    
        public virtual Nullable<int> BillingDaysOffset
        {
            get;
            set;
        }
    
        public virtual string OnErrorEmail
        {
            get;
            set;
        }
    
        public virtual string MSNCampaignURL
        {
            get;
            set;
        }
    
        public virtual string MSNCampagnNamespace
        {
            get;
            set;
        }
    
        public virtual string MSNCustomerURL
        {
            get;
            set;
        }
    
        public virtual string MSNCustomerNamespace
        {
            get;
            set;
        }
    
        public virtual string MSNReportingURL
        {
            get;
            set;
        }
    
        public virtual string MSNReportingNamespace
        {
            get;
            set;
        }
    
        public virtual string MSNAdIntelligenceURL
        {
            get;
            set;
        }
    
        public virtual string MSNAdIntelligenceNamespace
        {
            get;
            set;
        }
    
        public virtual Nullable<long> MSNParentCustomerID
        {
            get;
            set;
        }
    
        public virtual string MSNApiUsername
        {
            get;
            set;
        }
    
        public virtual string MSNApiPassword
        {
            get;
            set;
        }
    
        public virtual string MSNUserAccessKey
        {
            get;
            set;
        }
    
        public virtual string AdwordsEmail
        {
            get;
            set;
        }
    
        public virtual string AdwordsPassword
        {
            get;
            set;
        }
    
        public virtual string AdwordsUserAgent
        {
            get;
            set;
        }
    
        public virtual string AdwordsDeveloperToken
        {
            get;
            set;
        }
    
        public virtual string OrbitalGatewaySalemPlatform
        {
            get;
            set;
        }
    
        public virtual string OrbitalGatewayMerchantID
        {
            get;
            set;
        }
    
        public virtual string OrbitalGatewayUsername
        {
            get;
            set;
        }
    
        public virtual string OrbitalGatewayPassword
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestClientAdwordsTimeoutMS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestClientKeywordTimeoutMS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestClientBiddingTimeoutMS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestClientMailTimeoutMS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestClientSchedulerTimeoutMS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestClientMSNTimeoutMS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestBiddingMaxRetry
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestBiddingSleepPeriod
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestBiddingSleepBackOffTime
        {
            get;
            set;
        }
    
        public virtual Nullable<long> SemplestBiddingMaxMicroBid
        {
            get;
            set;
        }
    
        public virtual Nullable<long> SemplestBiddingStepAboveFpCPC
        {
            get;
            set;
        }
    
        public virtual Nullable<long> SemplestBiddingDefaultMicroBid
        {
            get;
            set;
        }
    
        public virtual Nullable<long> SemplestBiddingMaxDefaultMicroBid
        {
            get;
            set;
        }
    
        public virtual Nullable<long> SemplestBiddingStepFirst
        {
            get;
            set;
        }
    
        public virtual Nullable<long> SemplestBiddingStepSecond
        {
            get;
            set;
        }
    
        public virtual Nullable<long> SemplestBiddingStepRest
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestBiddingGooglePercent
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ESBRegServicePort
        {
            get;
            set;
        }
    
        public virtual string ESBBrokerName
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ESBBrokerPort
        {
            get;
            set;
        }
    
        public virtual string ESBBrokerIP
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ESBWebServerPort
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ESBHeaderBufferSize
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ESBAsynchServletCorePoolSize
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ESBAsynchServletMaxPoolSize
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ESBAsynchServletMaxWorkInQueue
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ESBAsynchCallDefaultTimeoutMS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ServiceESBServerPort
        {
            get;
            set;
        }
    
        public virtual string ServiceESBServerIP
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ServicePingFrequencyMS
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ServiceNumberServiceThreads
        {
            get;
            set;
        }
    
        public virtual string ServiceSMTP
        {
            get;
            set;
        }
    
        public virtual string ESBWebServerURL
        {
            get;
            set;
        }
    
        public virtual bool AdwordsUseSandbox
        {
            get;
            set;
        }
    
        public virtual string SemplestEncryptionkey
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordsdictfile
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordsdocfile
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordstwfile
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordsdfile
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordsbaseMultiWPath
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordsnGramsSubC
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordsnGramsC
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordsvalidCat
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordslucenedfile
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordssmallhCounts
        {
            get;
            set;
        }
    
        public virtual string SemplestKeywordsstoplist
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestKeywordsnumTopics
        {
            get;
            set;
        }
    
        public virtual Nullable<double> SemplestKeywordsuserInfoWeight
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestKeywordsnumKeywordsGoogle
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestKeywordsnumKeywordsMSN
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SemplestKeywordsnumThreads
        {
            get;
            set;
        }
    
        public virtual bool DisplayTargetCPCLevel
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ServiceESBPingWaitMS
        {
            get;
            set;
        }
    
        public virtual string AdwordsBillingAccount
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> AdwordsAPICostPer1000
        {
            get;
            set;
        }

        #endregion
    }
}
