//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardProfile
    {
        public CreditCardProfile()
        {
            this.CreditCardTransactions = new HashSet<CreditCardTransaction>();
        }
    
        public int CreditCardProfilePK { get; set; }
        public int CustomerFK { get; set; }
        public string CustomerRefNum { get; set; }
        public string AuthCode { get; set; }
        public string TxRefNum { get; set; }
        public string ProfileNickname { get; set; }
    
        public virtual ICollection<CreditCardTransaction> CreditCardTransactions { get; set; }
    }
}
