//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class Credential
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int CredentialPK { get; set; }

        public int UsersFK { get; set; }
        
        public string Username { get; set; }
        
        public string Password { get; set; }
        
        public bool RememberMe { get; set; }
        
        public string SecurityQuestion { get; set; }
        
        public string SecurityAnswer { get; set; }

        [ForeignKey("UsersFK")]
        public virtual User User { get; set; }
    }
    
}
