//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class Credential
    {
        #region Primitive Properties
    
        public virtual int CredentialPK
        {
            get;
            set;
        }
    
        public virtual int UsersFK
        {
            get { return _usersFK; }
            set
            {
                if (_usersFK != value)
                {
                    if (User != null && User.UserPK != value)
                    {
                        User = null;
                    }
                    _usersFK = value;
                }
            }
        }
        private int _usersFK;
    
        public virtual string Username
        {
            get;
            set;
        }
    
        public virtual string Password
        {
            get;
            set;
        }
    
        public virtual bool RememberMe
        {
            get;
            set;
        }
    
        public virtual string SecurityQuestion
        {
            get;
            set;
        }
    
        public virtual string SecurityAnswer
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Credentials.Contains(this))
            {
                previousValue.Credentials.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Credentials.Contains(this))
                {
                    User.Credentials.Add(this);
                }
                if (UsersFK != User.UserPK)
                {
                    UsersFK = User.UserPK;
                }
            }
        }

        #endregion
    }
}
