//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class CreditCardTransaction
    {
        #region Primitive Properties
    
        public virtual int CreditCardTransactionPK
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CreditCardProfileFK
        {
            get { return _creditCardProfileFK; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_creditCardProfileFK != value)
                    {
                        if (CreditCardProfile != null && CreditCardProfile.CreditCardProfilePK != value)
                        {
                            CreditCardProfile = null;
                        }
                        _creditCardProfileFK = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _creditCardProfileFK;
    
        public virtual string OrderID
        {
            get;
            set;
        }
    
        public virtual decimal Amount
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual decimal SEMplestFee
        {
            get;
            set;
        }
    
        public virtual decimal MediaSpend
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CreditCardProfile CreditCardProfile
        {
            get { return _creditCardProfile; }
            set
            {
                if (!ReferenceEquals(_creditCardProfile, value))
                {
                    var previousValue = _creditCardProfile;
                    _creditCardProfile = value;
                    FixupCreditCardProfile(previousValue);
                }
            }
        }
        private CreditCardProfile _creditCardProfile;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCreditCardProfile(CreditCardProfile previousValue)
        {
            if (previousValue != null && previousValue.CreditCardTransactions.Contains(this))
            {
                previousValue.CreditCardTransactions.Remove(this);
            }
    
            if (CreditCardProfile != null)
            {
                if (!CreditCardProfile.CreditCardTransactions.Contains(this))
                {
                    CreditCardProfile.CreditCardTransactions.Add(this);
                }
                if (CreditCardProfileFK != CreditCardProfile.CreditCardProfilePK)
                {
                    CreditCardProfileFK = CreditCardProfile.CreditCardProfilePK;
                }
            }
            else if (!_settingFK)
            {
                CreditCardProfileFK = null;
            }
        }

        #endregion
    }
}
