//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class CreditCardProfile
    {
        #region Primitive Properties
    
        public virtual int CreditCardProfilePK
        {
            get;
            set;
        }
    
        public virtual int CustomerFK
        {
            get;
            set;
        }
    
        public virtual string CustomerRefNum
        {
            get;
            set;
        }
    
        public virtual string AuthCode
        {
            get;
            set;
        }
    
        public virtual string TxRefNum
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<CreditCardTransaction> CreditCardTransactions
        {
            get
            {
                if (_creditCardTransactions == null)
                {
                    var newCollection = new FixupCollection<CreditCardTransaction>();
                    newCollection.CollectionChanged += FixupCreditCardTransactions;
                    _creditCardTransactions = newCollection;
                }
                return _creditCardTransactions;
            }
            set
            {
                if (!ReferenceEquals(_creditCardTransactions, value))
                {
                    var previousValue = _creditCardTransactions as FixupCollection<CreditCardTransaction>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCreditCardTransactions;
                    }
                    _creditCardTransactions = value;
                    var newValue = value as FixupCollection<CreditCardTransaction>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCreditCardTransactions;
                    }
                }
            }
        }
        private ICollection<CreditCardTransaction> _creditCardTransactions;

        #endregion
        #region Association Fixup
    
        private void FixupCreditCardTransactions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CreditCardTransaction item in e.NewItems)
                {
                    item.CreditCardProfile = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CreditCardTransaction item in e.OldItems)
                {
                    if (ReferenceEquals(item.CreditCardProfile, this))
                    {
                        item.CreditCardProfile = null;
                    }
                }
            }
        }

        #endregion
    }
}
