//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.AdvertisingEngineAccounts = new HashSet<AdvertisingEngineAccount>();
            this.CreditCardNickNames = new HashSet<CreditCardNickName>();
            this.CreditCardProfiles = new HashSet<CreditCardProfile>();
            this.CustomerHierarchies = new HashSet<CustomerHierarchy>();
            this.ProductGroups = new HashSet<ProductGroup>();
            this.CustomerAddressAssociations = new HashSet<CustomerAddressAssociation>();
            this.CustomerPhoneAssociations = new HashSet<CustomerPhoneAssociation>();
            this.WebContentQuestionMarkHelps = new HashSet<WebContentQuestionMarkHelp>();
            this.CustomerHierarchies1 = new HashSet<CustomerHierarchy>();
            this.CustomerNotes = new HashSet<CustomerNote>();
            this.EmailTemplates = new HashSet<EmailTemplate>();
            this.EmployeeCustomerAssociations = new HashSet<EmployeeCustomerAssociation>();
            this.Schedules = new HashSet<Schedule>();
            this.WebContents = new HashSet<WebContent>();
            this.Users = new HashSet<User>();
        }
    
        public int CustomerPK { get; set; }
        public string Name { get; set; }
        public decimal TotalTargetCycleBudget { get; set; }
        public int ProductGroupCycleTypeFK { get; set; }
        public int BillTypeFK { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public decimal ServiceFee { get; set; }
        public decimal PercentOfMedia { get; set; }
        public string InternalCustomerId { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public bool PromotionFeeOverride { get; set; }
        public Nullable<decimal> PromotionFeeAmount { get; set; }
        public bool AllowAutobid { get; set; }
    
        public virtual ICollection<AdvertisingEngineAccount> AdvertisingEngineAccounts { get; set; }
        public virtual BillType BillType { get; set; }
        public virtual ICollection<CreditCardNickName> CreditCardNickNames { get; set; }
        public virtual ICollection<CreditCardProfile> CreditCardProfiles { get; set; }
        public virtual ICollection<CustomerHierarchy> CustomerHierarchies { get; set; }
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
        public virtual ICollection<CustomerAddressAssociation> CustomerAddressAssociations { get; set; }
        public virtual ICollection<CustomerPhoneAssociation> CustomerPhoneAssociations { get; set; }
        public virtual ProductGroupCycleType ProductGroupCycleType { get; set; }
        public virtual ICollection<WebContentQuestionMarkHelp> WebContentQuestionMarkHelps { get; set; }
        public virtual ICollection<CustomerHierarchy> CustomerHierarchies1 { get; set; }
        public virtual ICollection<CustomerNote> CustomerNotes { get; set; }
        public virtual CustomerStyle CustomerStyle { get; set; }
        public virtual ICollection<EmailTemplate> EmailTemplates { get; set; }
        public virtual ICollection<EmployeeCustomerAssociation> EmployeeCustomerAssociations { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<WebContent> WebContents { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
