//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Address))]
    [KnownType(typeof(AddressType))]
    [KnownType(typeof(Customer))]
    public partial class CustomerAddressAssociation
    {
        [DataMember]
        public int AddressFK { get; set; }
        [DataMember]
        public int CustomerFK { get; set; }
        [DataMember]
        public int AddressTypeFK { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
    
        [DataMember]
        public virtual Address Address { get; set; }
        [DataMember]
        public virtual AddressType AddressType { get; set; }
        [DataMember]
        public virtual Customer Customer { get; set; }
    }
    
}
