//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class CustomerHierarchy
    {
        #region Primitive Properties
    
        public virtual int CustomerHierarchyPK
        {
            get;
            set;
        }
    
        public virtual int CustomerFK
        {
            get { return _customerFK; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_customerFK != value)
                    {
                        if (Customer != null && Customer.CustomerPK != value)
                        {
                            Customer = null;
                        }
                        _customerFK = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _customerFK;
    
        public virtual Nullable<int> CustomerParentFK
        {
            get { return _customerParentFK; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_customerParentFK != value)
                    {
                        if (Customer1 != null && Customer1.CustomerPK != value)
                        {
                            Customer1 = null;
                        }
                        _customerParentFK = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _customerParentFK;
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Customer Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private Customer _customer;
    
        public virtual Customer Customer1
        {
            get { return _customer1; }
            set
            {
                if (!ReferenceEquals(_customer1, value))
                {
                    var previousValue = _customer1;
                    _customer1 = value;
                    FixupCustomer1(previousValue);
                }
            }
        }
        private Customer _customer1;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCustomer(Customer previousValue)
        {
            if (previousValue != null && previousValue.CustomerHierarchies.Contains(this))
            {
                previousValue.CustomerHierarchies.Remove(this);
            }
    
            if (Customer != null)
            {
                if (!Customer.CustomerHierarchies.Contains(this))
                {
                    Customer.CustomerHierarchies.Add(this);
                }
                if (CustomerFK != Customer.CustomerPK)
                {
                    CustomerFK = Customer.CustomerPK;
                }
            }
        }
    
        private void FixupCustomer1(Customer previousValue)
        {
            if (previousValue != null && previousValue.CustomerHierarchies1.Contains(this))
            {
                previousValue.CustomerHierarchies1.Remove(this);
            }
    
            if (Customer1 != null)
            {
                if (!Customer1.CustomerHierarchies1.Contains(this))
                {
                    Customer1.CustomerHierarchies1.Add(this);
                }
                if (CustomerParentFK != Customer1.CustomerPK)
                {
                    CustomerParentFK = Customer1.CustomerPK;
                }
            }
            else if (!_settingFK)
            {
                CustomerParentFK = null;
            }
        }

        #endregion
    }
}
