//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class CustomerPhoneAssociation
    {
        [System.ComponentModel.DataAnnotations.Key,Column(Order = 1)]
        public int CustomerFK { get; set; }
        [System.ComponentModel.DataAnnotations.Key,Column(Order = 2)]
        public int PhoneFK { get; set; }
        
        public System.DateTime CreatedDate { get; set; }

        [ForeignKey("CustomerFK")]
        public virtual Customer Customer { get; set; }
        [ForeignKey("PhoneFK")]
        public virtual Phone Phone { get; set; }
    }
    
}
