//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class CustomerAddressAssociation
    {
        
        [Column(Order = 1),Key]
        public int AddressFK { get; set; }
        
        [Column(Order = 2),Key]
        public int CustomerFK { get; set; }
        
        public int AddressTypeFK { get; set; }
        
        public System.DateTime CreatedDate { get; set; }

        [ForeignKey("AddressFK")]
        public virtual Address Address { get; set; }
        [ForeignKey("AddressTypeFK")]
        public virtual AddressType AddressType { get; set; }
        [ForeignKey("CustomerFK")]
        public virtual Customer Customer { get; set; }
    }
    
}
