//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public int EmailTemplatePK { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string EmailFrom { get; set; }
        public int EmailTypeFK { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual EmailType EmailType { get; set; }
    }
}
