//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeCustomerAssociations = new HashSet<EmployeeCustomerAssociation>();
            this.EmployeePhoneAssociations = new HashSet<EmployeePhoneAssociation>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public int EmployeePK { get; set; }
        
        public int EmployeeTypeFK { get; set; }
        
        public int UsersFK { get; set; }
        
        public Nullable<int> ReportingTo { get; set; }
        
        public Nullable<System.DateTime> HireDate { get; set; }
    
        
        public virtual ICollection<EmployeeCustomerAssociation> EmployeeCustomerAssociations { get; set; }
        
        public virtual ICollection<EmployeePhoneAssociation> EmployeePhoneAssociations { get; set; }
        [ForeignKey("EmployeeTypeFK")]
        public virtual EmployeeType EmployeeType { get; set; }
        [ForeignKey("UsersFK")]
        public virtual User User { get; set; }
    }
    
}
