//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class EmployeeCustomerAssociation
    {
        #region Primitive Properties
    
        public virtual int EmployeeCustomerAssociationPK
        {
            get;
            set;
        }
    
        public virtual int CustomerFK
        {
            get { return _customerFK; }
            set
            {
                if (_customerFK != value)
                {
                    if (Customer != null && Customer.CustomerPK != value)
                    {
                        Customer = null;
                    }
                    _customerFK = value;
                }
            }
        }
        private int _customerFK;
    
        public virtual int EmployeeFK
        {
            get { return _employeeFK; }
            set
            {
                if (_employeeFK != value)
                {
                    if (Employee != null && Employee.EmployeePK != value)
                    {
                        Employee = null;
                    }
                    _employeeFK = value;
                }
            }
        }
        private int _employeeFK;

        #endregion
        #region Navigation Properties
    
        public virtual Customer Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private Customer _customer;
    
        public virtual Employee Employee
        {
            get { return _employee; }
            set
            {
                if (!ReferenceEquals(_employee, value))
                {
                    var previousValue = _employee;
                    _employee = value;
                    FixupEmployee(previousValue);
                }
            }
        }
        private Employee _employee;

        #endregion
        #region Association Fixup
    
        private void FixupCustomer(Customer previousValue)
        {
            if (previousValue != null && previousValue.EmployeeCustomerAssociations.Contains(this))
            {
                previousValue.EmployeeCustomerAssociations.Remove(this);
            }
    
            if (Customer != null)
            {
                if (!Customer.EmployeeCustomerAssociations.Contains(this))
                {
                    Customer.EmployeeCustomerAssociations.Add(this);
                }
                if (CustomerFK != Customer.CustomerPK)
                {
                    CustomerFK = Customer.CustomerPK;
                }
            }
        }
    
        private void FixupEmployee(Employee previousValue)
        {
            if (previousValue != null && previousValue.EmployeeCustomerAssociations.Contains(this))
            {
                previousValue.EmployeeCustomerAssociations.Remove(this);
            }
    
            if (Employee != null)
            {
                if (!Employee.EmployeeCustomerAssociations.Contains(this))
                {
                    Employee.EmployeeCustomerAssociations.Add(this);
                }
                if (EmployeeFK != Employee.EmployeePK)
                {
                    EmployeeFK = Employee.EmployeePK;
                }
            }
        }

        #endregion
    }
}
