//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class EmployeePhoneAssociation
    {
        #region Primitive Properties
    
        public virtual int PhoneFK
        {
            get { return _phoneFK; }
            set
            {
                if (_phoneFK != value)
                {
                    if (Phone != null && Phone.PhonePK != value)
                    {
                        Phone = null;
                    }
                    _phoneFK = value;
                }
            }
        }
        private int _phoneFK;
    
        public virtual int EmployeeFK
        {
            get { return _employeeFK; }
            set
            {
                if (_employeeFK != value)
                {
                    if (Employee != null && Employee.EmployeePK != value)
                    {
                        Employee = null;
                    }
                    _employeeFK = value;
                }
            }
        }
        private int _employeeFK;
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Employee Employee
        {
            get { return _employee; }
            set
            {
                if (!ReferenceEquals(_employee, value))
                {
                    var previousValue = _employee;
                    _employee = value;
                    FixupEmployee(previousValue);
                }
            }
        }
        private Employee _employee;
    
        public virtual Phone Phone
        {
            get { return _phone; }
            set
            {
                if (!ReferenceEquals(_phone, value))
                {
                    var previousValue = _phone;
                    _phone = value;
                    FixupPhone(previousValue);
                }
            }
        }
        private Phone _phone;

        #endregion
        #region Association Fixup
    
        private void FixupEmployee(Employee previousValue)
        {
            if (previousValue != null && previousValue.EmployeePhoneAssociations.Contains(this))
            {
                previousValue.EmployeePhoneAssociations.Remove(this);
            }
    
            if (Employee != null)
            {
                if (!Employee.EmployeePhoneAssociations.Contains(this))
                {
                    Employee.EmployeePhoneAssociations.Add(this);
                }
                if (EmployeeFK != Employee.EmployeePK)
                {
                    EmployeeFK = Employee.EmployeePK;
                }
            }
        }
    
        private void FixupPhone(Phone previousValue)
        {
            if (previousValue != null && previousValue.EmployeePhoneAssociations.Contains(this))
            {
                previousValue.EmployeePhoneAssociations.Remove(this);
            }
    
            if (Phone != null)
            {
                if (!Phone.EmployeePhoneAssociations.Contains(this))
                {
                    Phone.EmployeePhoneAssociations.Add(this);
                }
                if (PhoneFK != Phone.PhonePK)
                {
                    PhoneFK = Phone.PhonePK;
                }
            }
        }

        #endregion
    }
}
