//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class Error
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ErrorPK { get; set; }
        
        public string ErrorMessage { get; set; }
        
        public Nullable<int> ErrorID { get; set; }
        
        public Nullable<int> UsersFK { get; set; }
        
        public string ErrorSource { get; set; }
        
        public string ErrorClass { get; set; }
        
        public string ErrorDetails { get; set; }
        
        public System.DateTime CreatedDate { get; set; }

        [ForeignKey("UsersFK")]
        public virtual User User { get; set; }
    }
    
}
