//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class GeoTargeting
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int GeoTargetingPK { get; set; }
        
        public int PromotionFK { get; set; }
        
        public string Address { get; set; }
        
        public string City { get; set; }
        
        public Nullable<int> StateCodeFK { get; set; }
        
        public string Zip { get; set; }
        
        public Nullable<decimal> Longitude { get; set; }
        
        public Nullable<decimal> Latitude { get; set; }
        
        public Nullable<decimal> ProximityRadius { get; set; }

        [ForeignKey("PromotionFK")]
        public virtual Promotion Promotion { get; set; }
        
        [ForeignKey("StateCodeFK")]
        public virtual StateCode StateCode { get; set; }
    }
    
}
