//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Promotion))]
    public partial class KeywordCategory
    {
        [DataMember]
        public int KeywordCategoryPK { get; set; }
        [DataMember]
        public int PromotionFK { get; set; }
        [DataMember]
        public string KeywordCategory1 { get; set; }
    
        [DataMember]
        public virtual Promotion Promotion { get; set; }
    }
    
}
