//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class Keyword
    {
        #region Primitive Properties
    
        public virtual int KeywordPK
        {
            get;
            set;
        }
    
        public virtual string Keyword1
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EditedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<PromotionKeywordAssociation> PromotionKeywordAssociations
        {
            get
            {
                if (_promotionKeywordAssociations == null)
                {
                    var newCollection = new FixupCollection<PromotionKeywordAssociation>();
                    newCollection.CollectionChanged += FixupPromotionKeywordAssociations;
                    _promotionKeywordAssociations = newCollection;
                }
                return _promotionKeywordAssociations;
            }
            set
            {
                if (!ReferenceEquals(_promotionKeywordAssociations, value))
                {
                    var previousValue = _promotionKeywordAssociations as FixupCollection<PromotionKeywordAssociation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPromotionKeywordAssociations;
                    }
                    _promotionKeywordAssociations = value;
                    var newValue = value as FixupCollection<PromotionKeywordAssociation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPromotionKeywordAssociations;
                    }
                }
            }
        }
        private ICollection<PromotionKeywordAssociation> _promotionKeywordAssociations;

        #endregion
        #region Association Fixup
    
        private void FixupPromotionKeywordAssociations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PromotionKeywordAssociation item in e.NewItems)
                {
                    item.Keyword = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PromotionKeywordAssociation item in e.OldItems)
                {
                    if (ReferenceEquals(item.Keyword, this))
                    {
                        item.Keyword = null;
                    }
                }
            }
        }

        #endregion
    }
}
