//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class Keyword
    {
        public Keyword()
        {
            this.PromotionKeywordAssociations = new HashSet<PromotionKeywordAssociation>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public int KeywordPK { get; set; }
        [Column("Keyword")]
        public string Keyword1 { get; set; }
        
        public System.DateTime CreatedDate { get; set; }
        
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        
        public virtual ICollection<PromotionKeywordAssociation> PromotionKeywordAssociations { get; set; }
    }
    
}
