//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(AdvertisingEngine))]
    [KnownType(typeof(AdvertisingEngineReportData))]
    [KnownType(typeof(BidType))]
    [KnownType(typeof(KeywordBidData))]
    [KnownType(typeof(TrafficEstimator))]
    [KnownType(typeof(PromotionKeywordAssociation))]
    public partial class KeywordBid
    {
        public KeywordBid()
        {
            this.AdvertisingEngineReportDatas = new HashSet<AdvertisingEngineReportData>();
            this.KeywordBidDatas = new HashSet<KeywordBidData>();
            this.TrafficEstimators = new HashSet<TrafficEstimator>();
        }
    
        [DataMember]
        public int KeywordBidPK { get; set; }
        [DataMember]
        public int KeywordFK { get; set; }
        [DataMember]
        public int AdvertisingEngineFK { get; set; }
        [DataMember]
        public int PromotionFK { get; set; }
        [DataMember]
        public System.DateTime StartDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> EndDate { get; set; }
        [DataMember]
        public bool IsActive { get; set; }
        [DataMember]
        public int BidTypeFK { get; set; }
        [DataMember]
        public int MicroBidAmount { get; set; }
        [DataMember]
        public Nullable<long> KeywordAdEngineID { get; set; }
        [DataMember]
        public string CompetitionType { get; set; }
        [DataMember]
        public bool IsDefaultValue { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
    
        [DataMember]
        public virtual AdvertisingEngine AdvertisingEngine { get; set; }
        [DataMember]
        public virtual ICollection<AdvertisingEngineReportData> AdvertisingEngineReportDatas { get; set; }
        [DataMember]
        public virtual BidType BidType { get; set; }
        [DataMember]
        public virtual ICollection<KeywordBidData> KeywordBidDatas { get; set; }
        [DataMember]
        public virtual ICollection<TrafficEstimator> TrafficEstimators { get; set; }
        [DataMember]
        public virtual PromotionKeywordAssociation PromotionKeywordAssociation { get; set; }
    }
    
}
