//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class KeywordBidData
    {
        #region Primitive Properties
    
        public virtual int KeywordBidDataPK
        {
            get;
            set;
        }
    
        public virtual Nullable<int> QualityScore
        {
            get;
            set;
        }
    
        public virtual string ApprovalStatus
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FirstPageMicroCPC
        {
            get;
            set;
        }
    
        public virtual bool IsEligibleForShowing
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> KeywordBidFK
        {
            get { return _keywordBidFK; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_keywordBidFK != value)
                    {
                        if (KeywordBid != null && KeywordBid.KeywordBidPK != value)
                        {
                            KeywordBid = null;
                        }
                        _keywordBidFK = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _keywordBidFK;

        #endregion
        #region Navigation Properties
    
        public virtual KeywordBid KeywordBid
        {
            get { return _keywordBid; }
            set
            {
                if (!ReferenceEquals(_keywordBid, value))
                {
                    var previousValue = _keywordBid;
                    _keywordBid = value;
                    FixupKeywordBid(previousValue);
                }
            }
        }
        private KeywordBid _keywordBid;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupKeywordBid(KeywordBid previousValue)
        {
            if (previousValue != null && previousValue.KeywordBidDatas.Contains(this))
            {
                previousValue.KeywordBidDatas.Remove(this);
            }
    
            if (KeywordBid != null)
            {
                if (!KeywordBid.KeywordBidDatas.Contains(this))
                {
                    KeywordBid.KeywordBidDatas.Add(this);
                }
                if (KeywordBidFK != KeywordBid.KeywordBidPK)
                {
                    KeywordBidFK = KeywordBid.KeywordBidPK;
                }
            }
            else if (!_settingFK)
            {
                KeywordBidFK = null;
            }
        }

        #endregion
    }
}
