//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class PhoneType
    {
        #region Primitive Properties
    
        public virtual int PhoneTypePK
        {
            get;
            set;
        }
    
        public virtual string PhoneType1
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Phone> Phones
        {
            get
            {
                if (_phones == null)
                {
                    var newCollection = new FixupCollection<Phone>();
                    newCollection.CollectionChanged += FixupPhones;
                    _phones = newCollection;
                }
                return _phones;
            }
            set
            {
                if (!ReferenceEquals(_phones, value))
                {
                    var previousValue = _phones as FixupCollection<Phone>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPhones;
                    }
                    _phones = value;
                    var newValue = value as FixupCollection<Phone>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPhones;
                    }
                }
            }
        }
        private ICollection<Phone> _phones;

        #endregion
        #region Association Fixup
    
        private void FixupPhones(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Phone item in e.NewItems)
                {
                    item.PhoneType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Phone item in e.OldItems)
                {
                    if (ReferenceEquals(item.PhoneType, this))
                    {
                        item.PhoneType = null;
                    }
                }
            }
        }

        #endregion
    }
}
