//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class ProductGroup
    {
        #region Primitive Properties
    
        public virtual int ProductGroupPK
        {
            get;
            set;
        }
    
        public virtual int CustomerFK
        {
            get { return _customerFK; }
            set
            {
                if (_customerFK != value)
                {
                    if (Customer != null && Customer.CustomerPK != value)
                    {
                        Customer = null;
                    }
                    _customerFK = value;
                }
            }
        }
        private int _customerFK;
    
        public virtual string ProductGroupName
        {
            get;
            set;
        }
    
        public virtual System.DateTime StartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EditedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Customer Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private Customer _customer;
    
        public virtual ICollection<Promotion> Promotions
        {
            get
            {
                if (_promotions == null)
                {
                    var newCollection = new FixupCollection<Promotion>();
                    newCollection.CollectionChanged += FixupPromotions;
                    _promotions = newCollection;
                }
                return _promotions;
            }
            set
            {
                if (!ReferenceEquals(_promotions, value))
                {
                    var previousValue = _promotions as FixupCollection<Promotion>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPromotions;
                    }
                    _promotions = value;
                    var newValue = value as FixupCollection<Promotion>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPromotions;
                    }
                }
            }
        }
        private ICollection<Promotion> _promotions;
    
        public virtual ICollection<Schedule> Schedules
        {
            get
            {
                if (_schedules == null)
                {
                    var newCollection = new FixupCollection<Schedule>();
                    newCollection.CollectionChanged += FixupSchedules;
                    _schedules = newCollection;
                }
                return _schedules;
            }
            set
            {
                if (!ReferenceEquals(_schedules, value))
                {
                    var previousValue = _schedules as FixupCollection<Schedule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSchedules;
                    }
                    _schedules = value;
                    var newValue = value as FixupCollection<Schedule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSchedules;
                    }
                }
            }
        }
        private ICollection<Schedule> _schedules;

        #endregion
        #region Association Fixup
    
        private void FixupCustomer(Customer previousValue)
        {
            if (previousValue != null && previousValue.ProductGroups.Contains(this))
            {
                previousValue.ProductGroups.Remove(this);
            }
    
            if (Customer != null)
            {
                if (!Customer.ProductGroups.Contains(this))
                {
                    Customer.ProductGroups.Add(this);
                }
                if (CustomerFK != Customer.CustomerPK)
                {
                    CustomerFK = Customer.CustomerPK;
                }
            }
        }
    
        private void FixupPromotions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Promotion item in e.NewItems)
                {
                    item.ProductGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Promotion item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductGroup, this))
                    {
                        item.ProductGroup = null;
                    }
                }
            }
        }
    
        private void FixupSchedules(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Schedule item in e.NewItems)
                {
                    item.ProductGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Schedule item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductGroup, this))
                    {
                        item.ProductGroup = null;
                    }
                }
            }
        }

        #endregion
    }
}
