//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CreditCardTransaction))]
    [KnownType(typeof(Promotion))]
    public partial class PromotionPayment
    {
        [DataMember]
        public int PromotionPaymentPK { get; set; }
        [DataMember]
        public Nullable<int> PromotionFK { get; set; }
        [DataMember]
        public System.DateTime BudgetToAddDate { get; set; }
        [DataMember]
        public bool IsValid { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public Nullable<int> CreditCardTransactionFK { get; set; }
    
        [DataMember]
        public virtual CreditCardTransaction CreditCardTransaction { get; set; }
        [DataMember]
        public virtual Promotion Promotion { get; set; }
    }
    
}
