//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(AdvertisingEngineAd))]
    [KnownType(typeof(Promotion))]
    public partial class PromotionAd
    {
        public PromotionAd()
        {
            this.AdvertisingEngineAds = new HashSet<AdvertisingEngineAd>();
        }
    
        [DataMember]
        public int PromotionAdsPK { get; set; }
        [DataMember]
        public int PromotionFK { get; set; }
        [DataMember]
        public string AdTitle { get; set; }
        [DataMember]
        public string AdTextLine1 { get; set; }
        [DataMember]
        public string AdTextLine2 { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [DataMember]
        public virtual ICollection<AdvertisingEngineAd> AdvertisingEngineAds { get; set; }
        [DataMember]
        public virtual Promotion Promotion { get; set; }
    }
    
}
