//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Keyword))]
    [KnownType(typeof(KeywordBid))]
    [KnownType(typeof(Promotion))]
    public partial class PromotionKeywordAssociation
    {
        public PromotionKeywordAssociation()
        {
            this.KeywordBids = new HashSet<KeywordBid>();
        }
    
        [DataMember]
        public int KeywordFK { get; set; }
        [DataMember]
        public int PromotionFK { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public bool IsActive { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }
        [DataMember]
        public bool IsNegative { get; set; }
        [DataMember]
        public Nullable<double> SemplestProbability { get; set; }
        [DataMember]
        public bool IsTargetMSN { get; set; }
        [DataMember]
        public bool IsTargetGoogle { get; set; }
    
        [DataMember]
        public virtual Keyword Keyword { get; set; }
        [DataMember]
        public virtual ICollection<KeywordBid> KeywordBids { get; set; }
        [DataMember]
        public virtual Promotion Promotion { get; set; }
    }
    
}
