//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(AdvertisingEnginePromotion))]
    [KnownType(typeof(BudgetCycle))]
    [KnownType(typeof(GeoTargeting))]
    [KnownType(typeof(KeywordCategory))]
    [KnownType(typeof(ProductGroup))]
    [KnownType(typeof(PromotionAdEngineSelected))]
    [KnownType(typeof(PromotionAdengineStatu))]
    [KnownType(typeof(PromotionAd))]
    [KnownType(typeof(PromotionKeywordAssociation))]
    [KnownType(typeof(PromotionPayment))]
    [KnownType(typeof(Schedule))]
    [KnownType(typeof(SiteLink))]
    [KnownType(typeof(TargetedDailyBudget))]
    public partial class Promotion
    {
        public Promotion()
        {
            this.AdvertisingEnginePromotions = new HashSet<AdvertisingEnginePromotion>();
            this.GeoTargetings = new HashSet<GeoTargeting>();
            this.KeywordCategories = new HashSet<KeywordCategory>();
            this.PromotionAdEngineSelecteds = new HashSet<PromotionAdEngineSelected>();
            this.PromotionAdengineStatus = new HashSet<PromotionAdengineStatu>();
            this.PromotionAds = new HashSet<PromotionAd>();
            this.PromotionKeywordAssociations = new HashSet<PromotionKeywordAssociation>();
            this.PromotionPayments = new HashSet<PromotionPayment>();
            this.Schedules = new HashSet<Schedule>();
            this.SiteLinks = new HashSet<SiteLink>();
            this.TargetedDailyBudgets = new HashSet<TargetedDailyBudget>();
        }
    
        [DataMember]
        public int PromotionPK { get; set; }
        [DataMember]
        public int ProductGroupFK { get; set; }
        [DataMember]
        public string PromotionName { get; set; }
        [DataMember]
        public string PromotionDescription { get; set; }
        [DataMember]
        public System.DateTime PromotionStartDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> PromotionEndDate { get; set; }
        [DataMember]
        public string LandingPageURL { get; set; }
        [DataMember]
        public decimal PromotionBudgetAmount { get; set; }
        [DataMember]
        public int BudgetCycleFK { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CycleStartDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CycleEndDate { get; set; }
        [DataMember]
        public Nullable<decimal> StartBudgetInCycle { get; set; }
        [DataMember]
        public Nullable<decimal> RemainingBudgetInCycle { get; set; }
        [DataMember]
        public Nullable<decimal> BudgetToAddToNextCycle { get; set; }
        [DataMember]
        public Nullable<System.DateTime> BudgetToAddDate { get; set; }
        [DataMember]
        public bool IsPaused { get; set; }
        [DataMember]
        public bool IsCompleted { get; set; }
        [DataMember]
        public bool IsLaunched { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> EditedDate { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }
        [DataMember]
        public string TargetCPCLevel { get; set; }
        [DataMember]
        public string DisplayURL { get; set; }
    
        [DataMember]
        public virtual ICollection<AdvertisingEnginePromotion> AdvertisingEnginePromotions { get; set; }
        [DataMember]
        public virtual BudgetCycle BudgetCycle { get; set; }
        [DataMember]
        public virtual ICollection<GeoTargeting> GeoTargetings { get; set; }
        [DataMember]
        public virtual ICollection<KeywordCategory> KeywordCategories { get; set; }
        [DataMember]
        public virtual ProductGroup ProductGroup { get; set; }
        [DataMember]
        public virtual ICollection<PromotionAdEngineSelected> PromotionAdEngineSelecteds { get; set; }
        [DataMember]
        public virtual ICollection<PromotionAdengineStatu> PromotionAdengineStatus { get; set; }
        [DataMember]
        public virtual ICollection<PromotionAd> PromotionAds { get; set; }
        [DataMember]
        public virtual ICollection<PromotionKeywordAssociation> PromotionKeywordAssociations { get; set; }
        [DataMember]
        public virtual ICollection<PromotionPayment> PromotionPayments { get; set; }
        [DataMember]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [DataMember]
        public virtual ICollection<SiteLink> SiteLinks { get; set; }
        [DataMember]
        public virtual ICollection<TargetedDailyBudget> TargetedDailyBudgets { get; set; }
    }
    
}
