//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [Table("PromotionAds")]
    public partial class PromotionAd
    {
        public PromotionAd()
        {
            this.AdvertisingEngineAds = new HashSet<AdvertisingEngineAd>();
        }
    
        [DataMember,System.ComponentModel.DataAnnotations.Key]
        public int PromotionAdsPK { get; set; }
        
        public int PromotionFK { get; set; }
        
        public string AdTitle { get; set; }
        
        public string AdTextLine1 { get; set; }
        
        public string AdTextLine2 { get; set; }
        
        public bool IsDeleted { get; set; }
        
        public System.DateTime CreatedDate { get; set; }
        
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        
        public virtual ICollection<AdvertisingEngineAd> AdvertisingEngineAds { get; set; }
        [ForeignKey("PromotionFK")]
        public virtual Promotion Promotion { get; set; }
    }
    
}
