//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RolesRightsAssociation))]
    public partial class Right
    {
        public Right()
        {
            this.RolesRightsAssociations = new HashSet<RolesRightsAssociation>();
        }
    
        [DataMember]
        public int RightsPK { get; set; }
        [DataMember]
        public string Controller { get; set; }
        [DataMember]
        public string Label { get; set; }
    
        [DataMember]
        public virtual ICollection<RolesRightsAssociation> RolesRightsAssociations { get; set; }
    }
    
}
