//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class Role
    {
        #region Primitive Properties
    
        public virtual int RolePK
        {
            get;
            set;
        }
    
        public virtual string RoleName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<RolesRightsAssociation> RolesRightsAssociations
        {
            get
            {
                if (_rolesRightsAssociations == null)
                {
                    var newCollection = new FixupCollection<RolesRightsAssociation>();
                    newCollection.CollectionChanged += FixupRolesRightsAssociations;
                    _rolesRightsAssociations = newCollection;
                }
                return _rolesRightsAssociations;
            }
            set
            {
                if (!ReferenceEquals(_rolesRightsAssociations, value))
                {
                    var previousValue = _rolesRightsAssociations as FixupCollection<RolesRightsAssociation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRolesRightsAssociations;
                    }
                    _rolesRightsAssociations = value;
                    var newValue = value as FixupCollection<RolesRightsAssociation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRolesRightsAssociations;
                    }
                }
            }
        }
        private ICollection<RolesRightsAssociation> _rolesRightsAssociations;
    
        public virtual ICollection<UserRolesAssociation> UserRolesAssociations
        {
            get
            {
                if (_userRolesAssociations == null)
                {
                    var newCollection = new FixupCollection<UserRolesAssociation>();
                    newCollection.CollectionChanged += FixupUserRolesAssociations;
                    _userRolesAssociations = newCollection;
                }
                return _userRolesAssociations;
            }
            set
            {
                if (!ReferenceEquals(_userRolesAssociations, value))
                {
                    var previousValue = _userRolesAssociations as FixupCollection<UserRolesAssociation>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUserRolesAssociations;
                    }
                    _userRolesAssociations = value;
                    var newValue = value as FixupCollection<UserRolesAssociation>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUserRolesAssociations;
                    }
                }
            }
        }
        private ICollection<UserRolesAssociation> _userRolesAssociations;

        #endregion
        #region Association Fixup
    
        private void FixupRolesRightsAssociations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RolesRightsAssociation item in e.NewItems)
                {
                    item.Role = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RolesRightsAssociation item in e.OldItems)
                {
                    if (ReferenceEquals(item.Role, this))
                    {
                        item.Role = null;
                    }
                }
            }
        }
    
        private void FixupUserRolesAssociations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UserRolesAssociation item in e.NewItems)
                {
                    item.Role = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UserRolesAssociation item in e.OldItems)
                {
                    if (ReferenceEquals(item.Role, this))
                    {
                        item.Role = null;
                    }
                }
            }
        }

        #endregion
    }
}
