//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Customer))]
    [KnownType(typeof(Frequency))]
    [KnownType(typeof(ProductGroup))]
    [KnownType(typeof(Promotion))]
    [KnownType(typeof(ScheduleJob))]
    [KnownType(typeof(ScheduleTaskAssociation))]
    [KnownType(typeof(User))]
    public partial class Schedule
    {
        public Schedule()
        {
            this.ScheduleJobs = new HashSet<ScheduleJob>();
            this.ScheduleTaskAssociations = new HashSet<ScheduleTaskAssociation>();
        }
    
        [DataMember]
        public int SchedulePK { get; set; }
        [DataMember]
        public string ScheduleName { get; set; }
        [DataMember]
        public System.DateTime StartTime { get; set; }
        [DataMember]
        public Nullable<System.DateTime> EndDate { get; set; }
        [DataMember]
        public int FrequencyFK { get; set; }
        [DataMember]
        public bool IsEnabled { get; set; }
        [DataMember]
        public bool IsInactive { get; set; }
        [DataMember]
        public int CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public int EditedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> EditedDate { get; set; }
        [DataMember]
        public Nullable<int> PromotionFK { get; set; }
        [DataMember]
        public Nullable<int> CustomerFK { get; set; }
        [DataMember]
        public Nullable<int> ProductGroupFK { get; set; }
        [DataMember]
        public Nullable<int> UsersFK { get; set; }
    
        [DataMember]
        public virtual Customer Customer { get; set; }
        [DataMember]
        public virtual Frequency Frequency { get; set; }
        [DataMember]
        public virtual ProductGroup ProductGroup { get; set; }
        [DataMember]
        public virtual Promotion Promotion { get; set; }
        [DataMember]
        public virtual ICollection<ScheduleJob> ScheduleJobs { get; set; }
        [DataMember]
        public virtual ICollection<ScheduleTaskAssociation> ScheduleTaskAssociations { get; set; }
        [DataMember]
        public virtual User User { get; set; }
    }
    
}
