//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class ScheduleLog
    {
        #region Primitive Properties
    
        public virtual int ScheduleLogPK
        {
            get;
            set;
        }
    
        public virtual int ScheduleJobFK
        {
            get { return _scheduleJobFK; }
            set
            {
                if (_scheduleJobFK != value)
                {
                    if (ScheduleJob != null && ScheduleJob.ScheduleJobPK != value)
                    {
                        ScheduleJob = null;
                    }
                    _scheduleJobFK = value;
                }
            }
        }
        private int _scheduleJobFK;
    
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
        public virtual bool IsSuccessful
        {
            get;
            set;
        }
    
        public virtual string ErrorMessage
        {
            get;
            set;
        }
    
        public virtual bool IsComplete
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ScheduleJob ScheduleJob
        {
            get { return _scheduleJob; }
            set
            {
                if (!ReferenceEquals(_scheduleJob, value))
                {
                    var previousValue = _scheduleJob;
                    _scheduleJob = value;
                    FixupScheduleJob(previousValue);
                }
            }
        }
        private ScheduleJob _scheduleJob;

        #endregion
        #region Association Fixup
    
        private void FixupScheduleJob(ScheduleJob previousValue)
        {
            if (previousValue != null && previousValue.ScheduleLogs.Contains(this))
            {
                previousValue.ScheduleLogs.Remove(this);
            }
    
            if (ScheduleJob != null)
            {
                if (!ScheduleJob.ScheduleLogs.Contains(this))
                {
                    ScheduleJob.ScheduleLogs.Add(this);
                }
                if (ScheduleJobFK != ScheduleJob.ScheduleJobPK)
                {
                    ScheduleJobFK = ScheduleJob.ScheduleJobPK;
                }
            }
        }

        #endregion
    }
}
