//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleLog
    {
        public int ScheduleLogPK { get; set; }
        public int ScheduleJobFK { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsSuccessful { get; set; }
        public string ErrorMessage { get; set; }
        public bool IsComplete { get; set; }
    
        public virtual ScheduleJob ScheduleJob { get; set; }
    }
}
