//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;


namespace SemplestModel
{
    
    public partial class ScheduleJob
    {
        public ScheduleJob()
        {
            this.ScheduleLogs = new HashSet<ScheduleLog>();
        }

        [System.ComponentModel.DataAnnotations.Key]
        public int ScheduleJobPK { get; set; }
        
        public int ScheduleFK { get; set; }
        
        public System.DateTime ExecutionStartTime { get; set; }
        
        public bool IsSuccessful { get; set; }
        
        public bool IsComplete { get; set; }
        
        public System.DateTime CreatedDate { get; set; }
        
        public Nullable<System.DateTime> EditedDate { get; set; }

        [ForeignKey("ScheduleFK")]
        public virtual Schedule Schedule { get; set; }
        
        public virtual ICollection<ScheduleLog> ScheduleLogs { get; set; }
    }
    
}
