//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Schedule))]
    [KnownType(typeof(Task))]
    public partial class ScheduleTaskAssociation
    {
        [DataMember]
        public int TaskFK { get; set; }
        [DataMember]
        public int ScheduleFK { get; set; }
        [DataMember]
        public int TaskExecutionOrder { get; set; }
    
        [DataMember]
        public virtual Schedule Schedule { get; set; }
        [DataMember]
        public virtual Task Task { get; set; }
    }
    
}
