//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemplestTransaction
    {
        public int SemplestTransactionPK { get; set; }
        public Nullable<int> TransactionsFK { get; set; }
        public Nullable<int> TransactionTypeFK { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
