//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class SiteLink
    {
        #region Primitive Properties
    
        public virtual int SiteLInkPK
        {
            get;
            set;
        }
    
        public virtual int PromotionFK
        {
            get { return _promotionFK; }
            set
            {
                if (_promotionFK != value)
                {
                    if (Promotion != null && Promotion.PromotionPK != value)
                    {
                        Promotion = null;
                    }
                    _promotionFK = value;
                }
            }
        }
        private int _promotionFK;
    
        public virtual string LinkText
        {
            get;
            set;
        }
    
        public virtual string LinkURL
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Promotion Promotion
        {
            get { return _promotion; }
            set
            {
                if (!ReferenceEquals(_promotion, value))
                {
                    var previousValue = _promotion;
                    _promotion = value;
                    FixupPromotion(previousValue);
                }
            }
        }
        private Promotion _promotion;

        #endregion
        #region Association Fixup
    
        private void FixupPromotion(Promotion previousValue)
        {
            if (previousValue != null && previousValue.SiteLinks.Contains(this))
            {
                previousValue.SiteLinks.Remove(this);
            }
    
            if (Promotion != null)
            {
                if (!Promotion.SiteLinks.Contains(this))
                {
                    Promotion.SiteLinks.Add(this);
                }
                if (PromotionFK != Promotion.PromotionPK)
                {
                    PromotionFK = Promotion.PromotionPK;
                }
            }
        }

        #endregion
    }
}
