//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class SiteLink
    {
        #region Primitive Properties
    
        public virtual int SiteLInkPK
        {
            get;
            set;
        }
    
        public virtual int PromotionAdsFK
        {
            get { return _promotionAdsFK; }
            set
            {
                if (_promotionAdsFK != value)
                {
                    if (PromotionAd != null && PromotionAd.PromotionAdsPK != value)
                    {
                        PromotionAd = null;
                    }
                    _promotionAdsFK = value;
                }
            }
        }
        private int _promotionAdsFK;
    
        public virtual string LinkText
        {
            get;
            set;
        }
    
        public virtual string LinkURL
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual PromotionAd PromotionAd
        {
            get { return _promotionAd; }
            set
            {
                if (!ReferenceEquals(_promotionAd, value))
                {
                    var previousValue = _promotionAd;
                    _promotionAd = value;
                    FixupPromotionAd(previousValue);
                }
            }
        }
        private PromotionAd _promotionAd;

        #endregion
        #region Association Fixup
    
        private void FixupPromotionAd(PromotionAd previousValue)
        {
            if (previousValue != null && previousValue.SiteLinks.Contains(this))
            {
                previousValue.SiteLinks.Remove(this);
            }
    
            if (PromotionAd != null)
            {
                if (!PromotionAd.SiteLinks.Contains(this))
                {
                    PromotionAd.SiteLinks.Add(this);
                }
                if (PromotionAdsFK != PromotionAd.PromotionAdsPK)
                {
                    PromotionAdsFK = PromotionAd.PromotionAdsPK;
                }
            }
        }

        #endregion
    }
}
