//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Address))]
    [KnownType(typeof(GeoTargeting))]
    public partial class StateCode
    {
        public StateCode()
        {
            this.Addresses = new HashSet<Address>();
            this.GeoTargetings = new HashSet<GeoTargeting>();
        }
    
        [DataMember]
        public int StateAbbrPK { get; set; }
        [DataMember]
        public string StateAbbr { get; set; }
    
        [DataMember]
        public virtual ICollection<Address> Addresses { get; set; }
        [DataMember]
        public virtual ICollection<GeoTargeting> GeoTargetings { get; set; }
    }
    
}
