//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ScheduleTaskAssociation))]
    public partial class Task
    {
        public Task()
        {
            this.ScheduleTaskAssociations = new HashSet<ScheduleTaskAssociation>();
        }
    
        [DataMember]
        public int TaskPK { get; set; }
        [DataMember]
        public string ServiceName { get; set; }
        [DataMember]
        public string MethodName { get; set; }
        [DataMember]
        public string Parameters { get; set; }
    
        [DataMember]
        public virtual ICollection<ScheduleTaskAssociation> ScheduleTaskAssociations { get; set; }
    }
    
}
