//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class TrafficEstimator
    {
        #region Primitive Properties
    
        public virtual int TrafficEstimatorPK
        {
            get;
            set;
        }
    
        public virtual Nullable<int> KeywordBidFK
        {
            get { return _keywordBidFK; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_keywordBidFK != value)
                    {
                        if (KeywordBid != null && KeywordBid.KeywordBidPK != value)
                        {
                            KeywordBid = null;
                        }
                        _keywordBidFK = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _keywordBidFK;
    
        public virtual int MicroBid
        {
            get;
            set;
        }
    
        public virtual double AveMicroCost
        {
            get;
            set;
        }
    
        public virtual double AveNumberClicks
        {
            get;
            set;
        }
    
        public virtual Nullable<double> AvePosition
        {
            get;
            set;
        }
    
        public virtual Nullable<double> AveCPC
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual KeywordBid KeywordBid
        {
            get { return _keywordBid; }
            set
            {
                if (!ReferenceEquals(_keywordBid, value))
                {
                    var previousValue = _keywordBid;
                    _keywordBid = value;
                    FixupKeywordBid(previousValue);
                }
            }
        }
        private KeywordBid _keywordBid;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupKeywordBid(KeywordBid previousValue)
        {
            if (previousValue != null && previousValue.TrafficEstimators.Contains(this))
            {
                previousValue.TrafficEstimators.Remove(this);
            }
    
            if (KeywordBid != null)
            {
                if (!KeywordBid.TrafficEstimators.Contains(this))
                {
                    KeywordBid.TrafficEstimators.Add(this);
                }
                if (KeywordBidFK != KeywordBid.KeywordBidPK)
                {
                    KeywordBidFK = KeywordBid.KeywordBidPK;
                }
            }
            else if (!_settingFK)
            {
                KeywordBidFK = null;
            }
        }

        #endregion
    }
}
