//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    public partial class TransactionHistory
    {
        [DataMember]
        public int TransactionHistoryPK { get; set; }
        [DataMember]
        public int UserFK { get; set; }
        [DataMember]
        public System.DateTime TransactionDate { get; set; }
        [DataMember]
        public string TableName { get; set; }
        [DataMember]
        public string Field { get; set; }
        [DataMember]
        public string OldValue { get; set; }
        [DataMember]
        public string NewValue { get; set; }
    
        [DataMember]
        public virtual User User { get; set; }
    }
    
}
