//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.PromotionBudgets = new HashSet<PromotionBudget>();
            this.SemplestTransactions = new HashSet<SemplestTransaction>();
        }
    
        public int TransactionsPK { get; set; }
        public int CustomerFK { get; set; }
        public int PayTypeFK { get; set; }
        public int TransactionTypeFK { get; set; }
        public Nullable<int> CreditCardProfileFK { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual CreditCardProfile CreditCardProfile { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PayType PayType { get; set; }
        public virtual ICollection<PromotionBudget> PromotionBudgets { get; set; }
        public virtual ICollection<SemplestTransaction> SemplestTransactions { get; set; }
    }
}
