//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SemplestModel
{
    public partial class vwGetLivePromotionsForUser
    {
        #region Primitive Properties
    
        public virtual int PromotionPK
        {
            get;
            set;
        }
    
        public virtual string PromotionName
        {
            get;
            set;
        }
    
        public virtual int UserPK
        {
            get;
            set;
        }
    
        public virtual bool IsPaused
        {
            get;
            set;
        }
    
        public virtual bool IsCompleted
        {
            get;
            set;
        }
    
        public virtual bool IsLaunched
        {
            get;
            set;
        }
    
        public virtual bool IsDeleted
        {
            get;
            set;
        }

        #endregion
    }
}
