//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    public partial class vwGetLivePromotionsForUser
    {
        [DataMember]
        public int PromotionPK { get; set; }
        [DataMember]
        public string PromotionName { get; set; }
        [DataMember]
        public int UserPK { get; set; }
        [DataMember]
        public bool IsPaused { get; set; }
        [DataMember]
        public bool IsCompleted { get; set; }
        [DataMember]
        public bool IsLaunched { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }
    }
    
}
