//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace SemplestModel
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Customer))]
    public partial class WebContentQuestionMarkHelp
    {
        [DataMember]
        public int WebContentQuestionMarkHelpPK { get; set; }
        [DataMember]
        public Nullable<int> CustomerFK { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public string Copy { get; set; }
    
        [DataMember]
        public virtual Customer Customer { get; set; }
    }
    
}
