//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisingEngine
    {
        public AdvertisingEngine()
        {
            this.AdGroups = new HashSet<AdGroup>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int AdvertisingEnginePK { get; set; }
        public string AdvertisingEngine1 { get; set; }
    
        public virtual ICollection<AdGroup> AdGroups { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
