//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignCycleType
    {
        public CampaignCycleType()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int CampaignCycleTypePK { get; set; }
        public string CampaignCycleType1 { get; set; }
        public int CycleInDays { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
