#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResources.Views.Error
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<List<Semplest.SharedResources.Controllers.ErrorModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\Error\Index.cshtml"
  
    Layout = null;
    ViewBag.Title = "Index";


            
            #line default
            #line hidden
WriteLiteral("    <script src=\"");


            
            #line 7 "..\..\Views\Error\Index.cshtml"
            Write(Url.Content("~/Scripts/jquery-1.7.2.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"> </script>\r\n        <div class=\"editor-field\">\r\n        " +
"");


            
            #line 9 "..\..\Views\Error\Index.cshtml"
   Write(Html.DropDownList("ddl", ViewData["CreateDate"] as SelectList));

            
            #line default
            #line hidden
WriteLiteral("  \r\n        </div>\r\n        <div class= \"errors\">\r\n   <table border =1><tr><th>Us" +
"er</th><th>Error Message</th><th>Time Stamp</th></tr>\r\n");


            
            #line 13 "..\..\Views\Error\Index.cshtml"
   foreach (Semplest.SharedResources.Controllers.ErrorModel item in Model)
  {

            
            #line default
            #line hidden
WriteLiteral("  <tr>\r\n  <td>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 18 "..\..\Views\Error\Index.cshtml"
   Write(Html.DisplayFor(model => item.User));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    </td>\r\n<td>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 23 "..\..\Views\Error\Index.cshtml"
   Write(Html.DisplayFor(model => item.ErrorMessage));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    </td>\r\n    <td>\r\n    <div class=\"display-field\">\r\n        ");


            
            #line 28 "..\..\Views\Error\Index.cshtml"
   Write(Html.DisplayFor(model => item.TimeStamp));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    </td>\r\n    </tr>\r\n");


            
            #line 32 "..\..\Views\Error\Index.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral(@"  </table>   

  </div>

     <script  type=""text/javascript"">
         $(""select"").change(function () {
             $.ajax({
                 type: ""GET"",
                 url: ""/Error/GetData"",
                 data: { d: $(this).attr('value') },
                 success: function (data) { $('.errors').html(data); }
             });
         })
    </script>");


        }
    }
}
#pragma warning restore 1591
