//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionBidding
    {
        public int PromotionBiddingPK { get; set; }
        public int PromotionFK { get; set; }
        public int AdvertisingEngineFK { get; set; }
        public System.DateTime BidCompleted { get; set; }
        public Nullable<int> SemplestBidTypeFK { get; set; }
    
        public virtual AdvertisingEngine AdvertisingEngine { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
