//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class AdvertisingEngineAccount
    {
        public AdvertisingEngineAccount()
        {
            AdvertisingEngineCampaigns = new HashSet<AdvertisingEngineCampaign>();
        }

        public string AdvertisingEngineAccountPK { get; set; }
        public int AdvertisingEngineFK { get; set; }
        public int CustomerFK { get; set; }

        public virtual AdvertisingEngine AdvertisingEngine { get; set; }
        public virtual ICollection<AdvertisingEngineCampaign> AdvertisingEngineCampaigns { get; set; }
        public virtual Customer Customer { get; set; }
    }
}