//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class BidType
    {
        public BidType()
        {
            KeywordBids = new HashSet<KeywordBid>();
        }

        public int BidTypePK { get; set; }
        public string BidType1 { get; set; }

        public virtual ICollection<KeywordBid> KeywordBids { get; set; }
    }
}