//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semplest.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frequency
    {
        public Frequency()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int FrequencyPK { get; set; }
        public string Frequency1 { get; set; }
    
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
