//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semplest.Core.Models
{
    public class GeoTargeting
    {
        public int GeoTargetingPK { get; set; }
        public int PromotionFK { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int? StateCodeFK { get; set; }
        public string Zip { get; set; }
        public decimal? Longitude { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? ProximityRadius { get; set; }

        public virtual Promotion Promotion { get; set; }
    }
}