//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class KeywordBid
    {
        public KeywordBid()
        {
            AdvertisingEngineBidDatas = new HashSet<AdvertisingEngineBidData>();
        }

        public int KeywordBidPK { get; set; }
        public int KeywordFK { get; set; }
        public int PromotionFK { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool IsActive { get; set; }
        public int BidTypeFK { get; set; }
        public decimal BidAmount { get; set; }

        public virtual ICollection<AdvertisingEngineBidData> AdvertisingEngineBidDatas { get; set; }
        public virtual BidType BidType { get; set; }
        public virtual PromotionKeywordAssociation PromotionKeywordAssociation { get; set; }
    }
}