//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class Keyword
    {
        public Keyword()
        {
            PromotionKeywordAssociations = new HashSet<PromotionKeywordAssociation>();
        }

        public int KeywordPK { get; set; }
        public string Keyword1 { get; set; }
        public bool IsActive { get; set; }
        public bool ISNegative { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? EditedDate { get; set; }

        public virtual ICollection<PromotionKeywordAssociation> PromotionKeywordAssociations { get; set; }
    }
}