//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class Phone
    {
        public Phone()
        {
            CustomerPhoneAssociations = new HashSet<CustomerPhoneAssociation>();
        }

        public int PhonePK { get; set; }
        public string Phone1 { get; set; }
        public string Extension { get; set; }
        public int PhoneTypeFK { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? EditedDate { get; set; }

        public virtual ICollection<CustomerPhoneAssociation> CustomerPhoneAssociations { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}