//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semplest.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public sealed class ProductGroup
    {
        public ProductGroup()
        {
            Promotions = new HashSet<Promotion>();
            Schedules = new HashSet<Schedule>();
        }
    
        public int ProductGroupPK { get; set; }
        public int CustomerFK { get; set; }
        public string ProductGroupName { get; set; }
        public DateTime StartDate { get; set; }
        public Nullable<DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? EditedDate { get; set; }
    
        public Customer Customer { get; set; }
        public ICollection<Promotion> Promotions { get; set; }
        public ICollection<Schedule> Schedules { get; set; }
    }
}
