//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semplest.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.AdvertisingEngineCampaigns = new HashSet<AdvertisingEngineCampaign>();
            this.PromotionAds = new HashSet<PromotionAd>();
            this.PromotionKeywordAssociations = new HashSet<PromotionKeywordAssociation>();
            this.GeoTargetings = new HashSet<GeoTargeting>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int PromotionPK { get; set; }
        public int ProductGroupFK { get; set; }
        public string LandingPageURL { get; set; }
        public decimal CycleBudgetAmount { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsPaused { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string EditedDate { get; set; }
    
        public virtual ICollection<AdvertisingEngineCampaign> AdvertisingEngineCampaigns { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<PromotionAd> PromotionAds { get; set; }
        public virtual ICollection<PromotionKeywordAssociation> PromotionKeywordAssociations { get; set; }
        public virtual ICollection<GeoTargeting> GeoTargetings { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
