//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class PromotionKeywordAssociation
    {
        public PromotionKeywordAssociation()
        {
            KeywordBids = new HashSet<KeywordBid>();
        }

        public int KeywordFK { get; set; }
        public int PromotionFK { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual Keyword Keyword { get; set; }
        public virtual ICollection<KeywordBid> KeywordBids { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}