//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class Promotion
    {
        public Promotion()
        {
            AdvertisingEngineCampaigns = new HashSet<AdvertisingEngineCampaign>();
            PromotionAds = new HashSet<PromotionAd>();
            PromotionKeywordAssociations = new HashSet<PromotionKeywordAssociation>();
            GeoTargetings = new HashSet<GeoTargeting>();
            Schedules = new HashSet<Schedule>();
        }

        public int PromotionPK { get; set; }
        public int ProductGroupFK { get; set; }
        public string LandingPageURL { get; set; }
        public decimal CycleBudgetAmount { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool IsPaused { get; set; }
        public DateTime CreatedDate { get; set; }
        public string EditedDate { get; set; }

        public virtual ICollection<AdvertisingEngineCampaign> AdvertisingEngineCampaigns { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<PromotionAd> PromotionAds { get; set; }
        public virtual ICollection<PromotionKeywordAssociation> PromotionKeywordAssociations { get; set; }
        public virtual ICollection<GeoTargeting> GeoTargetings { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}