//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class Right
    {
        public Right()
        {
            RolesRightsAssociations = new HashSet<RolesRightsAssociation>();
        }

        public int RightsPK { get; set; }
        public string Controller { get; set; }
        public string Label { get; set; }

        public virtual ICollection<RolesRightsAssociation> RolesRightsAssociations { get; set; }
    }
}