//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Semplest.Core.Models
{
    public class Role
    {
        public Role()
        {
            RolesRightsAssociations = new HashSet<RolesRightsAssociation>();
            UserRolesAssociations = new HashSet<UserRolesAssociation>();
        }

        public int RolePK { get; set; }
        public string RoleName { get; set; }

        public virtual ICollection<RolesRightsAssociation> RolesRightsAssociations { get; set; }
        public virtual ICollection<UserRolesAssociation> UserRolesAssociations { get; set; }
    }
}