//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semplest.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTaskAssociation
    {
        public int TaskFK { get; set; }
        public int ScheduleFK { get; set; }
        public int TaskExecutionOrder { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
