#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResources.Views.Error
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/_ErrorView.cshtml")]
    public class ErrorView : System.Web.Mvc.WebViewPage<List<Semplest.SharedResources.Controllers.ErrorModel>>
    {
        public ErrorView()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Error\_ErrorView.cshtml"
  
    ViewBag.Title = "ErrorView";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table border =1 id =\"errorResults\"><tr><th>User</th><th>Error Message</th><t" +
"h>Time Stamp</th></tr>\r\n");


            
            #line 8 "..\..\Views\Error\_ErrorView.cshtml"
             foreach (Semplest.SharedResources.Controllers.ErrorModel item in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n                        <div clas" +
"s=\"display-field\">\r\n                            ");


            
            #line 13 "..\..\Views\Error\_ErrorView.cshtml"
                       Write(Html.DisplayFor(model => item.User));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </td>\r\n                    " +
"<td>\r\n                        <div class=\"display-field\">\r\n                     " +
"       ");


            
            #line 18 "..\..\Views\Error\_ErrorView.cshtml"
                       Write(Html.DisplayFor(model => item.ErrorMessage));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </td>\r\n                    " +
"<td>\r\n                        <div class=\"display-field\">\r\n                     " +
"       ");


            
            #line 23 "..\..\Views\Error\_ErrorView.cshtml"
                       Write(Html.DisplayFor(model => item.TimeStamp));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </td>\r\n                </tr" +
">\r\n");


            
            #line 27 "..\..\Views\Error\_ErrorView.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>   ");


        }
    }
}
#pragma warning restore 1591
