//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestAdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.CustomerHierarchies = new HashSet<CustomerHierarchy>();
            this.CustomerAddressAssociations = new HashSet<CustomerAddressAssociation>();
            this.CustomerPhoneAssociations = new HashSet<CustomerPhoneAssociation>();
            this.CustomerHierarchies1 = new HashSet<CustomerHierarchy>();
            this.Users = new HashSet<User>();
            this.AdvertisingEngines = new HashSet<AdvertisingEngine>();
        }
    
        public int CustomerPK { get; set; }
        public string Name { get; set; }
        public decimal TotalTargetCycleBudget { get; set; }
        public int CampaignCycleTypeFK { get; set; }
        public int BillTypeFK { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual BillType BillType { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual CampaignCycleType CampaignCycleType { get; set; }
        public virtual ICollection<CustomerHierarchy> CustomerHierarchies { get; set; }
        public virtual ICollection<CustomerAddressAssociation> CustomerAddressAssociations { get; set; }
        public virtual ICollection<CustomerPhoneAssociation> CustomerPhoneAssociations { get; set; }
        public virtual ICollection<CustomerHierarchy> CustomerHierarchies1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<AdvertisingEngine> AdvertisingEngines { get; set; }
    }
}
