//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestAdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Rights = new HashSet<Right>();
        }
    
        public int RolePK { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<Right> Rights { get; set; }
        public virtual User User { get; set; }
    }
}
