//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestAdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int transactionID { get; set; }
        public Nullable<int> UserFK { get; set; }
        public string TransactionType { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
