//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemplestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionStatu
    {
        public PromotionStatu()
        {
            this.PromotionAdengineStatus = new HashSet<PromotionAdengineStatu>();
        }
    
        public int PromotionStatusPK { get; set; }
        public string PromotionStatus { get; set; }
    
        public virtual ICollection<PromotionAdengineStatu> PromotionAdengineStatus { get; set; }
    }
}
