/**
 * ICampaignManagementService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.microsoft.adcenter.v8;

public interface ICampaignManagementService extends java.rmi.Remote {
    public com.microsoft.adcenter.v8.GetAdExtensionsByCampaignIdsResponse getAdExtensionsByCampaignIds(com.microsoft.adcenter.v8.GetAdExtensionsByCampaignIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAdExtensionsByIdsResponse getAdExtensionsByIds(com.microsoft.adcenter.v8.GetAdExtensionsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetAdExtensionsToCampaignsResponse setAdExtensionsToCampaigns(com.microsoft.adcenter.v8.SetAdExtensionsToCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.EditorialApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteAdExtensionsFromCampaignsResponse deleteAdExtensionsFromCampaigns(com.microsoft.adcenter.v8.DeleteAdExtensionsFromCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAdsByEditorialStatusResponse getAdsByEditorialStatus(com.microsoft.adcenter.v8.GetAdsByEditorialStatusRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAdsByIdsResponse getAdsByIds(com.microsoft.adcenter.v8.GetAdsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAdsByAdGroupIdResponse getAdsByAdGroupId(com.microsoft.adcenter.v8.GetAdsByAdGroupIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateAdsResponse updateAds(com.microsoft.adcenter.v8.UpdateAdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.EditorialApiFaultDetail;
    public com.microsoft.adcenter.v8.PauseAdsResponse pauseAds(com.microsoft.adcenter.v8.PauseAdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.ResumeAdsResponse resumeAds(com.microsoft.adcenter.v8.ResumeAdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddKeywordsResponse addKeywords(com.microsoft.adcenter.v8.AddKeywordsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.EditorialApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteKeywordsResponse deleteKeywords(com.microsoft.adcenter.v8.DeleteKeywordsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetKeywordsByEditorialStatusResponse getKeywordsByEditorialStatus(com.microsoft.adcenter.v8.GetKeywordsByEditorialStatusRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetKeywordsByIdsResponse getKeywordsByIds(com.microsoft.adcenter.v8.GetKeywordsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetKeywordsByAdGroupIdResponse getKeywordsByAdGroupId(com.microsoft.adcenter.v8.GetKeywordsByAdGroupIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.PauseKeywordsResponse pauseKeywords(com.microsoft.adcenter.v8.PauseKeywordsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.ResumeKeywordsResponse resumeKeywords(com.microsoft.adcenter.v8.ResumeKeywordsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateKeywordsResponse updateKeywords(com.microsoft.adcenter.v8.UpdateKeywordsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.EditorialApiFaultDetail;
    public com.microsoft.adcenter.v8.AddBusinessesResponse addBusinesses(com.microsoft.adcenter.v8.AddBusinessesRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateBusinessesResponse updateBusinesses(com.microsoft.adcenter.v8.UpdateBusinessesRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteBusinessesResponse deleteBusinesses(com.microsoft.adcenter.v8.DeleteBusinessesRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetBusinessesInfoResponse getBusinessesInfo(com.microsoft.adcenter.v8.GetBusinessesInfoRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetBusinessesByIdsResponse getBusinessesByIds(com.microsoft.adcenter.v8.GetBusinessesByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddSitePlacementsResponse addSitePlacements(com.microsoft.adcenter.v8.AddSitePlacementsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteSitePlacementsResponse deleteSitePlacements(com.microsoft.adcenter.v8.DeleteSitePlacementsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetSitePlacementsByIdsResponse getSitePlacementsByIds(com.microsoft.adcenter.v8.GetSitePlacementsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetSitePlacementsByAdGroupIdResponse getSitePlacementsByAdGroupId(com.microsoft.adcenter.v8.GetSitePlacementsByAdGroupIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.PauseSitePlacementsResponse pauseSitePlacements(com.microsoft.adcenter.v8.PauseSitePlacementsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.ResumeSitePlacementsResponse resumeSitePlacements(com.microsoft.adcenter.v8.ResumeSitePlacementsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateSitePlacementsResponse updateSitePlacements(com.microsoft.adcenter.v8.UpdateSitePlacementsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetPlacementDetailsForUrlsResponse getPlacementDetailsForUrls(com.microsoft.adcenter.v8.GetPlacementDetailsForUrlsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetNormalizedStringsResponse getNormalizedStrings(com.microsoft.adcenter.v8.GetNormalizedStringsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetKeywordEditorialReasonsByIdsResponse getKeywordEditorialReasonsByIds(com.microsoft.adcenter.v8.GetKeywordEditorialReasonsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAdEditorialReasonsByIdsResponse getAdEditorialReasonsByIds(com.microsoft.adcenter.v8.GetAdEditorialReasonsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DownloadCampaignHierarchyResponse downloadCampaignHierarchy(com.microsoft.adcenter.v8.DownloadCampaignHierarchyRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetDownloadStatusResponse getDownloadStatus(com.microsoft.adcenter.v8.GetDownloadStatusRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddGoalsResponse addGoals(com.microsoft.adcenter.v8.AddGoalsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail, com.microsoft.adcenter.v8.AnalyticsApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateGoalsResponse updateGoals(com.microsoft.adcenter.v8.UpdateGoalsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail, com.microsoft.adcenter.v8.AnalyticsApiFaultDetail;
    public com.microsoft.adcenter.v8.GetGoalsResponse getGoals(com.microsoft.adcenter.v8.GetGoalsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteGoalsResponse deleteGoals(com.microsoft.adcenter.v8.DeleteGoalsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetAnalyticsTypeResponse setAnalyticsType(com.microsoft.adcenter.v8.SetAnalyticsTypeRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAnalyticsTypeResponse getAnalyticsType(com.microsoft.adcenter.v8.GetAnalyticsTypeRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetCampaignAdExtensionsResponse getCampaignAdExtensions(com.microsoft.adcenter.v8.GetCampaignAdExtensionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetCampaignAdExtensionsResponse setCampaignAdExtensions(com.microsoft.adcenter.v8.SetCampaignAdExtensionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.EditorialApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAccountMigrationStatusesResponse getAccountMigrationStatuses(com.microsoft.adcenter.v8.GetAccountMigrationStatusesRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddAdExtensionsResponse addAdExtensions(com.microsoft.adcenter.v8.AddAdExtensionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddCampaignsResponse addCampaigns(com.microsoft.adcenter.v8.AddCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetCampaignsByAccountIdResponse getCampaignsByAccountId(com.microsoft.adcenter.v8.GetCampaignsByAccountIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetCampaignsByIdsResponse getCampaignsByIds(com.microsoft.adcenter.v8.GetCampaignsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.PauseCampaignsResponse pauseCampaigns(com.microsoft.adcenter.v8.PauseCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.ResumeCampaignsResponse resumeCampaigns(com.microsoft.adcenter.v8.ResumeCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteCampaignsResponse deleteCampaigns(com.microsoft.adcenter.v8.DeleteCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateCampaignsResponse updateCampaigns(com.microsoft.adcenter.v8.UpdateCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetNegativeKeywordsByCampaignIdsResponse getNegativeKeywordsByCampaignIds(com.microsoft.adcenter.v8.GetNegativeKeywordsByCampaignIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetNegativeKeywordsToCampaignsResponse setNegativeKeywordsToCampaigns(com.microsoft.adcenter.v8.SetNegativeKeywordsToCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetNegativeSitesByCampaignIdsResponse getNegativeSitesByCampaignIds(com.microsoft.adcenter.v8.GetNegativeSitesByCampaignIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetNegativeSitesToCampaignsResponse setNegativeSitesToCampaigns(com.microsoft.adcenter.v8.SetNegativeSitesToCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddAdGroupsResponse addAdGroups(com.microsoft.adcenter.v8.AddAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteAdGroupsResponse deleteAdGroups(com.microsoft.adcenter.v8.DeleteAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAdGroupsByIdsResponse getAdGroupsByIds(com.microsoft.adcenter.v8.GetAdGroupsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetAdGroupsByCampaignIdResponse getAdGroupsByCampaignId(com.microsoft.adcenter.v8.GetAdGroupsByCampaignIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.PauseAdGroupsResponse pauseAdGroups(com.microsoft.adcenter.v8.PauseAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.ResumeAdGroupsResponse resumeAdGroups(com.microsoft.adcenter.v8.ResumeAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SubmitAdGroupForApprovalResponse submitAdGroupForApproval(com.microsoft.adcenter.v8.SubmitAdGroupForApprovalRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateAdGroupsResponse updateAdGroups(com.microsoft.adcenter.v8.UpdateAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetNegativeKeywordsByAdGroupIdsResponse getNegativeKeywordsByAdGroupIds(com.microsoft.adcenter.v8.GetNegativeKeywordsByAdGroupIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetNegativeKeywordsToAdGroupsResponse setNegativeKeywordsToAdGroups(com.microsoft.adcenter.v8.SetNegativeKeywordsToAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetNegativeSitesByAdGroupIdsResponse getNegativeSitesByAdGroupIds(com.microsoft.adcenter.v8.GetNegativeSitesByAdGroupIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetNegativeSitesToAdGroupsResponse setNegativeSitesToAdGroups(com.microsoft.adcenter.v8.SetNegativeSitesToAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddTargetResponse addTarget(com.microsoft.adcenter.v8.AddTargetRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteTargetResponse deleteTarget(com.microsoft.adcenter.v8.DeleteTargetRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetTargetByAdGroupIdResponse getTargetByAdGroupId(com.microsoft.adcenter.v8.GetTargetByAdGroupIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateTargetResponse updateTarget(com.microsoft.adcenter.v8.UpdateTargetRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddTargetsToLibraryResponse addTargetsToLibrary(com.microsoft.adcenter.v8.AddTargetsToLibraryRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateTargetsInLibraryResponse updateTargetsInLibrary(com.microsoft.adcenter.v8.UpdateTargetsInLibraryRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.UpdateDeviceOSTargetsResponse updateDeviceOSTargets(com.microsoft.adcenter.v8.UpdateDeviceOSTargetsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteTargetsFromLibraryResponse deleteTargetsFromLibrary(com.microsoft.adcenter.v8.DeleteTargetsFromLibraryRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetTargetsInfoFromLibraryResponse getTargetsInfoFromLibrary(com.microsoft.adcenter.v8.GetTargetsInfoFromLibraryRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetTargetsByIdsResponse getTargetsByIds(com.microsoft.adcenter.v8.GetTargetsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetDeviceOSTargetsByIdsResponse getDeviceOSTargetsByIds(com.microsoft.adcenter.v8.GetDeviceOSTargetsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetTargetToAdGroupResponse setTargetToAdGroup(com.microsoft.adcenter.v8.SetTargetToAdGroupRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteTargetFromAdGroupResponse deleteTargetFromAdGroup(com.microsoft.adcenter.v8.DeleteTargetFromAdGroupRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetTargetsByAdGroupIdsResponse getTargetsByAdGroupIds(com.microsoft.adcenter.v8.GetTargetsByAdGroupIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.SetTargetToCampaignResponse setTargetToCampaign(com.microsoft.adcenter.v8.SetTargetToCampaignRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteTargetFromCampaignResponse deleteTargetFromCampaign(com.microsoft.adcenter.v8.DeleteTargetFromCampaignRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.GetTargetsByCampaignIdsResponse getTargetsByCampaignIds(com.microsoft.adcenter.v8.GetTargetsByCampaignIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
    public com.microsoft.adcenter.v8.AddAdsResponse addAds(com.microsoft.adcenter.v8.AddAdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.EditorialApiFaultDetail;
    public com.microsoft.adcenter.v8.DeleteAdsResponse deleteAds(com.microsoft.adcenter.v8.DeleteAdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.adapi.AdApiFaultDetail, com.microsoft.adcenter.v8.ApiFaultDetail;
}
