#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResources.Views.Error
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<List<Semplest.SharedResources.Controllers.ErrorModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\Error\Index.cshtml"
  
    Layout = null;
    ViewBag.Title = "Index";


            
            #line default
            #line hidden
WriteLiteral("<script src=\"");


            
            #line 7 "..\..\Views\Error\Index.cshtml"
        Write(Url.Content("~/Scripts/jquery-1.7.2.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"> </script>\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    $(d" +
"ocument).ready(function () {\r\n        $(\"select\").change(function () {\r\n        " +
"    $(\'#errorForm\').submit();\r\n        });\r\n    });\r\n\r\n</script>\r\n");


            
            #line 18 "..\..\Views\Error\Index.cshtml"
 using (Html.BeginForm("ErrorView", "Error", new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "errorResults" },FormMethod.Get, new { id = "errorForm" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"editor-field\">\r\n        ");


            
            #line 21 "..\..\Views\Error\Index.cshtml"
   Write(Html.DropDownList("ddl", ViewData["CreateDate"] as SelectList));

            
            #line default
            #line hidden
WriteLiteral("  \r\n    </div>\r\n");


            
            #line 23 "..\..\Views\Error\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    <div id= \"errorResults\">\r\n       ");


            
            #line 25 "..\..\Views\Error\Index.cshtml"
  Write(Html.Partial("_ErrorView", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </div>\r\n");


        }
    }
}
#pragma warning restore 1591
